version: '3'
services:
  webapp:
    image: webdevops/php-apache:7.3
    container_name: slim-demo-webapp
    ports:
      - "8080:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DISPLAY_ERRORS: 1
      VIRTUAL_HOST: slim-demo.random21.com

    volumes:
      - ./:/app

networks:
  default:
    external:
      name: nginx-proxy
    